### ISSUE TITLE
Missing artifact it.polimi.sr.rsp:api:jar:1.0.0

### ISSUE THREAD

**Issue by ValentinaIvanova** [streamreasoning/rsp4j#21]
Hello!

I am trying to install RSP4J using Eclipse Maven project. As soon as I add the dependency to com.github.streamreasoning.rsp4j:yasper:1.0.0 using Maven --> Add Dependency dialog I get the following error message in the pom file: Missing artifact it.polimi.sr.rsp:api:jar:1.0.0
(I have the jitpack.io repository already added. Additionally, I could not find this library anywhere.) 

Many thanks in advance for the help.

Valentina

**Comment by pbonte** [comment]
Hi Valentina,

Yes you are right, we need to update the artifacts on jitpack.
In the mean time, I think its easiest if you cloned the repo and installed it using maven:
```
git clone https://github.com/streamreasoning/rsp4j.git
cd rsp4j
mvn clean install
```
Or you can use the dependency for the example repo, which contains all rsp4j dependencies as well:
```
	<dependency>
	    <groupId>com.github.streamreasoning.rsp4j</groupId>
	    <artifactId>examples</artifactId>
	    <version>1.1.3</version>
	</dependency>
```

Let me know if this works for you.

KR,
Pieter

**Comment by ValentinaIvanova** [comment]
Hi Pieter,

Many thanks for the extremely quick reply. Added the dependency to the example repo and it worked.

Many thanks,
Valentina
